### ISSUE TITLE
Add function for Delete button

### ISSUE THREAD

**Issue by Bisig1892** [KnightShade07/TeamSourceControlDemo#44]
add function for delete in the edit delete screen

**Comment by KnightShade07** [comment]
Tried calling Delete function in DeleteBtn_Click, forgot how to call function correctly.
![DeleteBtn function](https://user-images.githubusercontent.com/45324806/90571758-4c86b880-e167-11ea-9297-396eb1d1d598.PNG)

**Comment by Bisig1892** [comment]
I finished the delete button. Just about to push it to github.
