### ISSUE TITLE
Final Tests Before Submission

### ISSUE THREAD

**Issue by KnightShade07** [KnightShade07/TeamSourceControlDemo#61]
Before submitting to Canvas, give the recipe application a final test. See if it can:
- Add Recipes to the Database.
- Edit/Update Recipes to the Database.
- Delete Recipes from the Database

Also, make sure everything is spelled correctly,  and make sure that the grammar checks out.

Make a comment on your test findings down below.

This issue can be closed once both assignees test the project.

**Comment by KnightShade07** [comment]
- Show Recipe Functionality Works, with all the information displaying correctly in the text boxes.
- Add Recipe Functions correctly, with the text clearing itself after submission for the next recipe.
- Refresh Recipe List Button works correctly, with a user-friendly notification to give them some tips.
- Update Functionality works correctly, the user just needs to hit the refresh button after updating, as live implementation was deemed to be too difficult and time-consuming for this project.
- Delete Functionality works correctly, deleting a recipe from the database.
- All exit buttons successfully close out of their forms/the application itself.
- All Tests passed!

**Comment by Bisig1892** [comment]
Testing complete
