### ISSUE TITLE
Update recipe

### ISSUE THREAD

**Issue by Bisig1892** [KnightShade07/TeamSourceControlDemo#7]
Add a function to update or insert new information on recipes

**Comment by KnightShade07** [comment]
Working on Update Recipe right now, just trying to get Source Control Issues fixed:
![Failed Push](https://user-images.githubusercontent.com/45324806/90357628-71b0e500-e008-11ea-8999-89f840358364.PNG)

**Comment by KnightShade07** [comment]
Master was behind a few commits, am now working on Update Recipe function successfully

**Comment by KnightShade07** [comment]
Still does not work. Have tried nearly everything:
![Git Branch Behind](https://user-images.githubusercontent.com/45324806/90359121-db32f280-e00c-11ea-89a9-90c16783759c.PNG)

**Comment by KnightShade07** [comment]
Problem magically fixed itself, I do not know how or why, but I'll take it!

**Comment by KnightShade07** [comment]
Update Functionality was added, just need to add to the button on Edit/Delete Recipe Page, see #40
